# This configuration file is used by the stats tool.
#
---
colors:
    title:             yellow_1
    delta:             cyan
    exceeds_threshold: magenta_1
    default:           white
    series:            green
    package:           yellow_1
    bg_odd_rows:       black
    bg_even_rows:      grey_11
    skew:              wheat_1

# When calculating the number of days a stage in the process takes, the result is compared to
# the maximum allocated time for that stage and if it's exceeded then the result is displayed
# in a different color (see above).
#
thresholds:
    total:             1900840 # 22 days
    ready:               86400 #  1 day
    waiting:             43200 # .5 days
    crank:                7200 #  2 hrs
    build:               21600 #  6 hrs
    proposed:            43200 # .5 days
    review_start:        43200 # .5 days
    review:              43200 # .5 days
    release:             86400 #  1 day
    bt:                   7200 #  2 hrs
    rt:                  86400 #  1 day
    at:                  86400 #  1 day
    sru:                  7200 #  2 hrs
    new:                  7200 #  2 hrs
