#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawTextHelpFormatter
from lib.bug                            import BugHelper

if __name__ == '__main__':
    app_description = '''List all of the SRU cycles known about in the database.
    '''
    app_epilog = '''
Examples:
    ./ls-cycles --stable | tail -n 1
            This should tell you what the current cycle is.
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawTextHelpFormatter)
    parser.add_argument('--stable', action='store_true', default=False, help='Stable cycles only')
    parser.add_argument('--dev', action='store_true', default=False, help='Development cycles only')
    args = parser.parse_args()

    q = 'select distinct cycle from bugs where cycle is not null and cycle != \'None\' and cycle <> \'\' order by cycle;'
    for r in BugHelper().query(q):
        print("%s" % r['cycle'])
